### ISSUE TITLE
Issues reported from Twitter user @ForrisHilier

### ISSUE THREAD

**Issue by lawsie** [raspberrypilearning/remote-control-buggy#12]
1) In 'Remotely control your buggy', under 'A home-brew remote control'
Error - 'PiGPIOFactory' object is not callable

2) In 'Using GPIO pins on a remote Raspberry Pi'
led = LED(rem_pi(17)) should be;
led = LED(17, pin_factory=rem_pi)
as per gpiozero docs

3/)Also, 'sudo pigpiod' is not needed if you have enabled Remote GPIO in Raspberry Pi Config GUI
https://t.co/41H0URpQs5
(not sure if this one is relevant or not)

Please can you have a look @MarcScott when you get back?

**Comment by MarcScott** [comment]
This issue has been fixed, and from my testing I still need to run `sudo pigpiod` to get it to work. Closing for now, but will re-open if needed after talking to @bennuttall

**Comment by bennuttall** [comment]
If you enable remote GPIO in rcgui, it does two things: allows remote connections and launches the daemon for that session, so you'll find you don't need to run `sudo pigpiod` that time, but you will after a reboot. I need to firm up the docs on that.
